name: Clojure CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
    - name: Deploy to clojars
      run: lein deploy clojars
